public enum BOOSTER_TYPE
{
	NONE = 0,
	SINGLE_BREAKER = 1,
	COLUMN_BREAKER = 2,
	ROW_BREAKER = 3,
	RAINBOW_BREAKER = 4,
	OVEN_BREAKER = 5,
	BEGIN_FIVE_MOVES = 6,
	BEGIN_RAINBOW_BREAKER = 7,
	BEGIN_BOMB_BREAKER = 8
}
